//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace biblioteca.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bibliotecadbEntities : DbContext
    {
        public bibliotecadbEntities()
            : base("name=bibliotecadbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_AUTOR> T_AUTOR { get; set; }
        public virtual DbSet<T_COPIA> T_COPIA { get; set; }
        public virtual DbSet<T_ESTADO> T_ESTADO { get; set; }
        public virtual DbSet<T_LECTOR> T_LECTOR { get; set; }
        public virtual DbSet<T_LIBRO> T_LIBRO { get; set; }
        public virtual DbSet<T_PRESTAMO> T_PRESTAMO { get; set; }
        public virtual DbSet<T_TIPO> T_TIPO { get; set; }
    }
}
